-- Tags with relations included

DROP TABLE IF EXISTS tags;
DROP SEQUENCE IF EXISTS tags_seq;

CREATE SEQUENCE tags_seq;

CREATE TABLE tags (
  id int NOT NULL DEFAULT NEXTVAL ('tags_seq'),
  name varchar(45) NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  CONSTRAINT TAG_UNIQUE UNIQUE  (name)
);

ALTER SEQUENCE tags_seq RESTART WITH 1;


